### PR TITLE
Omniauth-Oauth v 1.4

### PR DESCRIPTION
**Pull request by gfauredumont**
Hi again,

For the same reason I did my previous PR,
I just wanted to propose the provider with updated omniauth-oauth v 1.4
Same as before, tests results on Travis are the same as they are on your master.

Cheers

### CODE REVIEW

**Comment by simi** [comment]
Hello! Thanks for pull request. I think you can use `omniauth-oauth2` in 1.4 version without this change also. What's the motivation behind this pull request? Do you have any problems with older version or with version setup?

You can see [CI is using 1.4.0](https://travis-ci.org/mkdynamic/omniauth-facebook/jobs/149017591#L444) for latest master build without this change.

**Comment by gfauredumont** [comment]
Hi,
The motivation behind this PR is that we are using [rSpotify](https://github.com/guilhermesad/rspotify) in our project and it depends on omniauth-oauth2 v1.3.1
The only way I could bundle the project with your gem is by using my fork with the dependency changed to oauth 1.3.1 (#260).

I don't get how you can use omniauth-oauth2 v1.3.1 in a bundle without this modification on your gem :/

**Comment by simi** [comment]
`rSpotify` is locked to [1.3.x version](https://github.com/guilhermesad/rspotify/blob/35fe50a976855ff93d5ed8370d1a7843094e6a6e/rspotify.gemspec#L19).

I have no problem to resolve this Gemfile locally:

```ruby
source 'https://rubygems.org'

gem 'omniauth-facebook', '4.0.0'
gem 'rspotify'
```

It will install 1.3.1 `omniauth-oauth2`.

**Comment by gfauredumont** [comment]
I just tried it again with the initial configuration that was causing an issue but everything went fine !
I'm really sorry for disturbing you about a non-problem :/
As I can't reproduce what happened, I don't know why I couldn't bundle 2 days ago but indeed everything is fine.

I don't understand either why a gem with a dependency with `~> 1.0.0` would allow to use a `v 1.1.0`.
Isn't `~> 1.0.0` supposed to allow only updates on minor `1.0.x` versions ?!

Thanks a lot for taking the time to reply and showing me I'm wrong !
And sorry again for taking your time.

**Comment by simi** [comment]
@gfauredumont no need to sorry. It is still better and easier to prove that reported issue is wrong than fixing error and releasing new version.

Maybe there was problem with bundler if you added new dependency. Which gem uses ~`> 1.0.0` version constraint? You're right; `~> 1.0.0` should allow only `1.0.x` versions.

**Comment by gfauredumont** [comment]
OK, learned something more today: 
`~> 1.2` doesn't allow `1.2.x` but `1.x` !
That's why you didn't write `~> 1.2.0` in your [Gemspec](https://github.com/mkdynamic/omniauth-facebook/blob/master/omniauth-facebook.gemspec#L19) !!

Thanks again !

**Comment by simi** [comment]
@gfauredumont exactly!

**Pull request closed without merging**
