### PR TITLE
separate class for Facebook signed request parsing

### PR DESCRIPTION
**Pull request by simi**
@Vrael what do you think?

### CODE REVIEW

**Comment by Vrael** [comment]
@simi It seems perfect! Sorry for delaying.

**Comment by simi** [comment]
:confetti_ball:

**Comment by mkdynamic** [comment]
:trumpet:

**Comment by agrobbin** [comment]
@simi any chance this can be released as 2.1.0?

**Comment by simi** [comment]
@agrobbin sure

**Pull request merged**
