### PR TITLE
Use SVG Travis badge, add gem version badge

### PR DESCRIPTION
**Pull request by olivierlacan**
Looks sharper on all screen densities, latest gem version is relatively important and not immediately obvious, I think that would be useful.

### CODE REVIEW

**Comment by simi** [comment]
You're like open-source nomad for README badges. Thanks for your work @olivierlacan!

**Comment by olivierlacan** [comment]
:-)

**Comment by mkdynamic** [comment]
Haha. Nice.

**Comment by guilhermesimoes** [comment]
Well, it's because of him that such shiny badges exist! http://olivierlacan.com/posts/an-open-source-rage-diamond/

It's just too bad that open source maintainers don't know about these better badges D:

**Pull request merged**
